export const pets = [
  {
    id: 1,
    pet_name: "Jarrad",
    pet_role: "Dimmock",
    activity: "quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea",
    src: "/images/profiles/pp-1.jpg",
  },
  {
    id: 2,
    pet_name: "Gabbi",
    pet_role: "Brockington",
    activity: "volutpat erat quisque erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper",
    src: "/images/profiles/pp-2.jpg",
  },
  {
    id: 3,
    pet_name: "Stacey",
    pet_role: "Gittens",
    activity: "ac neque duis bibendum morbi non quam nec dui luctus rutrum",
    src: "/images/profiles/pp-3.jpg",
  },
  {
    id: 4,
    pet_name: "Ethel",
    pet_role: "Casham",
    activity: "lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus sit",
    src: "/images/profiles/pp-4.jpg",
  },
  {
    id: 5,
    pet_name: "Prinz",
    pet_role: "Gowlett",
    activity: "vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices",
    src: "/images/profiles/pp-5.jpg",
  },
  {
    id: 6,
    pet_name: "Anallese",
    pet_role: "Pennaman",
    activity: "erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus",
    src: "/images/profiles/pp-6.jpg",
  },
  {
    id: 7,
    pet_name: "Kelsey",
    pet_role: "Lupton",
    activity: "sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse",
    src: "/images/profiles/pp-7.jpg",
  },
  {
    id: 8,
    pet_name: "Farly",
    pet_role: "Kendle",
    activity: "odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non",
    src: "/images/profiles/pp-8.jpg",
  },
  {
    id: 9,
    pet_name: "Zaccaria",
    pet_role: "Olivari",
    activity: "mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum",
    src: "/images/profiles/pp-9.jpg",
  },
  {
    id: 10,
    pet_name: "Niall",
    pet_role: "Oldford",
    activity: "dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim",
    src: "/images/profiles/pp-10.jpg",
  },
  {
    id: 11,
    pet_name: "Betteann",
    pet_role: "Carlick",
    activity: "risus semper porta volutpat quam pede lobortis ligula sit amet",
    src: "/images/profiles/pp-11.jpg",
  },
  {
    id: 12,
    pet_name: "Arielle",
    pet_role: "Berceros",
    activity: "ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus",
    src: "/images/profiles/pp-12.jpg",
  },
  {
    id: 13,
    pet_name: "Juliet",
    pet_role: "Wallege",
    activity: "mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer",
    src: "/images/profiles/pp-13.jpg",
  },
  {
    id: 14,
    pet_name: "Bradley",
    pet_role: "Lilloe",
    activity: "in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in leo maecenas pulvinar",
    src: "/images/profiles/pp-14.jpg",
  },
  {
    id: 15,
    pet_name: "Maxie",
    pet_role: "Peirazzi",
    activity: "cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut suscipit a",
    src: "/images/profiles/pp-15.jpg",
  },
  {
    id: 16,
    pet_name: "Aliza",
    pet_role: "Denial",
    activity: "in leo maecenas pulvinar lobortis est phasellus sit amet erat",
    src: "/images/profiles/pp-16.jpg",
  },
];